spring:
  application:
    name: reconone
  datasource:
    url: jdbc:mariadb://localhost:3306/mydatabase
    username: myuser
    password: mypassword
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    mongodb:
      host: localhost
      port: 27017
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

server:
    port: 8080

kafka:
  topic:
    processedData: processed-data

camel:
  main:
    name: etlApplication
    auto-startup: false
    routes-collector-enabled: false
    tracing: false
  springboot:
    main-run-controller: true

instance:
  id: instance1 # Unique ID for this instance

pipelines:
  # List of pipelines to enable for this VM instance
  enabled: pipeline1, pipeline2, pipeline3
  # Check if auto start of pipeline is to read from database or config. Possible value is config or database
  startPriority: config
  # List of pipelines to auto start
  start: pipeline1, pipeline2, pipeline3

# Configuration for pipeline1
pipeline1:
  source:
    folder: inputFolder
  target:
    folder: outputFolder

# Configuration for pipeline2
pipeline2:
  source:
    kafka:
      topic: myTopic

# Configuration for pipeline3
pipeline3:
  source:
    folder: inputFolderChunk
  target:
    folder: outputFolderChunk

management:
  endpoint:
    health:
      show-details: always

